// <auto-generated />
using CarddyPartyBackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarddyPartyBackEnd.Migrations
{
    [DbContext(typeof(CarddyPartyBackEndContext))]
    [Migration("20210405215120_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CarddyPartyBackEnd.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Answer = "Card One",
                            PlayerId = 1
                        },
                        new
                        {
                            CardId = 2,
                            Answer = "Card Two",
                            PlayerId = 2
                        },
                        new
                        {
                            CardId = 3,
                            Answer = "Card Three",
                            PlayerId = 1
                        },
                        new
                        {
                            CardId = 4,
                            Answer = "Card Four",
                            PlayerId = 2
                        },
                        new
                        {
                            CardId = 5,
                            Answer = "Card Five",
                            PlayerId = 1
                        },
                        new
                        {
                            CardId = 6,
                            Answer = "Card Six",
                            PlayerId = 2
                        },
                        new
                        {
                            CardId = 7,
                            Answer = "Card Seven",
                            PlayerId = 1
                        },
                        new
                        {
                            CardId = 8,
                            Answer = "Card Eight",
                            PlayerId = 2
                        },
                        new
                        {
                            CardId = 9,
                            Answer = "Card Nine",
                            PlayerId = 1
                        },
                        new
                        {
                            CardId = 10,
                            Answer = "Card Ten",
                            PlayerId = 2
                        });
                });

            modelBuilder.Entity("CarddyPartyBackEnd.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CarddyPartyBackEnd.Models.Prompt", b =>
                {
                    b.Property<int>("PromptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Desciprtion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PromptId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("CarddyPartyBackEnd.Models.Card", b =>
                {
                    b.HasOne("CarddyPartyBackEnd.Models.Player", null)
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarddyPartyBackEnd.Models.Player", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
